### ISSUE TITLE
Link to private repository found

### ISSUE THREAD

**Issue by hiltonlima** [project-chip/certification-tool-frontend#7]
On file `/certification-tool/frontend/docs/development/Test_Harness_Frontend_Development_Environment_Setup_Windows/Test_Harness_Frontend_Development_Environment_Setup_Windows.adoc`

Private link at line number 89:
`https://github.com/CHIP-Specifications/chip-certification-tool-frontend/tree/develop`

Can we replace the private link with the link to the public repository?
`https://github.com/project-chip/certification-tool-frontend/tree/main`

**Comment by raul-marquez-csa** [comment]
Addressed in this PR:
[Updates doc repo link #8](https://github.com/project-chip/certification-tool-frontend/pull/8)
